name: Build & Test
on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:
jobs:
  Build-And-Test:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: agogpixel/foundation-dfromd
      BAKE_TARGETS: 3.14 3.13 3.12 3.11 edge
      TEST_TAGS: 3.14 3.13 3.12 3.11 edge
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker Login
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build
        run: IMAGE_NAME="${IMAGE_NAME}" IMAGE_TAG="$(git rev-parse --short HEAD)" docker buildx bake --no-cache --pull ${BAKE_TARGETS}
      - name: Test
        run: for TAG in ${TEST_TAGS}; do bash test.sh "${IMAGE_NAME}:${TAG}"; done
